version: '3'
services:
  lab-cyber-academy:
    build: ./
    image: 'lab-cyber-academy/web-terminal:latest'
    container_name: lab-cyber-academy
    volumes:
      - ./config.toml:/root/config.toml
    ports:
      - '9000:9000'
